# -*- coding: utf-8 -*-
"""Copy of Video Preprocess for pix2pix

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QCSm-r5u0piAYmGjtXhVVgkKfqj_gnhd

## Settings
"""

#@markdown This cell is to mount your Google Drive in Colaboratory. Run it and follow the instruction.

# mount_point = '/FaceEvo' #@param {type:'string'}

# import os
# if os.path.isdir(mount_point):
#   print(mount_point + ' has been already mounted.')
# else:
#   from google.colab import drive
#   drive.mount(mount_point)

#@markdown This cell contains some parameters. Update and run it.

input_file = 'source.mp4' #@param {type:"string"}
# input_file = mount_point + input_file

output_dir = 'AtoB' #@param {type:"string"}
# output_dir = mount_point + output_dir

"""## Preprocessing"""

import os
import cv2
import numpy as np
import skimage.io, skimage.transform, skimage.util

vid = cv2.VideoCapture(input_file)
count = 0

while True:
  available, frame = vid.read()
  if not available: break

  frame = frame[:, :, (2, 1, 0)]
  
  frame = skimage.transform.rescale(frame, 256.0 / frame.shape[0], 3, 'edge')

  crop = (frame.shape[1] - 256) / 2
  frame = skimage.util.crop(frame, ((0, 0), (crop, crop), (0, 0)))
  
  if count > 0:
    combined = np.concatenate((prev_frame, frame), axis = 1)
    combined = (combined * 255).astype(np.uint8)
    
    output_file = os.path.join(output_dir, 'frame%04d.png' % count)
    print(output_file)
    skimage.io.imsave(output_file, combined)
    
    #import matplotlib.pyplot as plt
    #plt.imshow(combined)
    #break
    
  prev_frame = frame
  count += 1

